### ISSUE TITLE
Train the Model with Other Midi Music

### ISSUE THREAD

**Issue by MilesQLi** [jisungk/deepjazz#9]
I tried to train the model with other music, but it failed. I think the problems come from this two lines:

    melody_stream = midi_data[5]     # For Metheny piece, Melody is Part #5.
    melody1, melody2 = melody_stream.getElementsByClass(stream.Voice)

**Comment by kylesnowschwartz** [comment]
The model is highly dependant on the structure of the midi file used, and musical structure of the piece itself. For example, the generator assumes your accompaniments are chord based (i.e., piano). You'll have to dig deeper if you want to use it with other pieces of music.

**Comment by MilesQLi** [comment]
Gotcha. Thank you very much.

**Comment by leesurkis** [comment]
Did you manage to find a way around using the model for other music? I came across an issue at the same 2 lines of code
